events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

#pr les logs 
    log_format log_per_virtualhost '[$host] $remote_addr [$time_local]  $status '
                                   '"$request" $body_bytes_sent';

#pr les logs aussi
    access_log /dev/stdout log_per_virtualhost;

    server {
        listen 8080;
       
        server_name www.l1-4.ephec-ti.be;

        location / {
            root /var/www/html/www;
            index index.html index.htm;
        }
#location en dessous est pr php, si besoin le mettre dans blog en changeant l'empacement (remplacer www par blog)
	location ~* \.php$ {
            fastcgi_pass 172.17.0.5:9000;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME /var/www/html/www$fastcgi_script_name;
        }
    }
   server {
	
	listen 8080;

	server_name blog.l1-4.ephec-ti.be;

        location / {
            root /var/www/html/blog;
            index index.html index.htm;
        }

   }
}
