services:

  db:
    image: mariadb:11.4
    container_name: mariadb-service
    restart: always
    volumes:
      - ./php/db/woodytoys.sql:/docker-entrypoint-initdb.d/woodytoys.sql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root_password_secours}
# php
  php:
    build: ./php
    container_name: php-service
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    volumes:
      - ./web/html/www:/var/www/html/www
    depends_on:
      - db


# Service Web (Nginx)
  web:
    build: ./web
    container_name: nginx-service
    ports:
      - "80:80"
    volumes:
      - ./web/html:/var/www/html
    depends_on:
      - php

  bind:
    build: ./bind
    container_name: dns-service
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    restart: always
