options {
  directory "/var/cache/bind";

  // Cache la version de Bind pour la sécurité
  version "not currently available";

  // Autorise tout le monde à interroger notre zone
  allow-query { any; };

  // Interdit la récursion pour ne pas être un "Open Resolver"
  recursion no;
  allow-query-cache { none; };
};

zone "l1-4.ephec-ti.be." {
  type master;
  file "/etc/bind/zones/l1-4.ephec-ti.be.zone";
  
  // Interdit le transfert de zone à des inconnus
  allow-transfer { none; };

  // Activation automatique de DNSSEC
  inline-signing yes;
  dnssec-policy default;
};
